---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-release.yml@641e8b22034b8eb49e2bbc11ef103d1324eb93e2 # main
    name: GitHub Release
